# Generated by Django 5.2.6 on 2025-10-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendingmessages', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="UserProfile"),
                migrations.DeleteModel(name="EmailConfirmation"),
            ],
        ),
    ]
